import {BrowserRouter,Routes,Route,Link,useNavigate,useParams,Navigate} from "react-router-dom";
import {useEffect,useMemo,useState} from "react";

const assignments=[
 {id:1,title:"Personal Portfolio",path:"/a1"},
 {id:2,title:"Student Information",path:"/a2"},
 {id:3,title:"Employee Directory",path:"/a3"},
 {id:4,title:"Weather Dashboard",path:"/a4"},
 {id:5,title:"Shopping Cart",path:"/a5"},
 {id:6,title:"Task Manager",path:"/a6"},
 {id:7,title:"Authentication System",path:"/a7"}
];

function Layout({children}){return <><header><Link className="brand" to="/">React Assignment 1–7</Link><nav>{assignments.map(a=><Link key={a.id} to={a.path}>A{a.id}</Link>)}</nav></header><main>{children}</main><footer>React JS Assignment 1–7 • 2026</footer></>}

function Home(){return <section className="hero"><span className="badge">College Assignment</span><h1>React JS Assignment 1–7</h1><p>Simple, responsive and submission-ready demonstrations of React components, props, state, API integration, routing and authentication.</p><div className="grid">{assignments.map(a=><Link className="tile" key={a.id} to={a.path}><b>Assignment {a.id}</b><span>{a.title}</span></Link>)}</div></section>}

function A1(){return <section><h1>Assignment 1: Personal Portfolio</h1><div className="portfolio"><h2>Biswajit</h2><p>Student • React & Cloud Computing Learner</p><h3>About Me</h3><p>I am a student learning programming, React and modern web development.</p><h3>Education</h3><p>B.Tech • Techno India University</p><h3>Skills</h3><div className="chips">{["HTML","CSS","JavaScript","React","C"].map(x=><span key={x}>{x}</span>)}</div><h3>Contact</h3><p>Email: student@example.com</p></div></section>}

function A2(){const initial=[{name:"Rahul",roll:"101",dept:"CSE",sem:"1st",cgpa:8.5},{name:"Riya",roll:"102",dept:"CSE",sem:"1st",cgpa:9.1},{name:"Amit",roll:"103",dept:"IT",sem:"1st",cgpa:7.8}];const [students,setStudents]=useState(initial);return <section><h1>Assignment 2: Student Information</h1><button onClick={()=>setStudents([...students].sort((a,b)=>b.cgpa-a.cgpa))}>Sort by CGPA</button><div className="grid">{students.map(s=><div className="card" key={s.roll}><h3>{s.name}</h3><p>Roll: {s.roll}</p><p>Department: {s.dept}</p><p>Semester: {s.sem}</p><p>CGPA: {s.cgpa}</p><div className="avatar">Student Photo</div></div>)}</div></section>}

function A3(){const [employees,setEmployees]=useState([{id:1,name:"Amit",dept:"IT",gender:"Male",phone:"9876543210",local:"Kolkata",permanent:"Kolkata"}]);const empty={name:"",dept:"IT",gender:"",phone:"",local:"",permanent:""};const [form,setForm]=useState(empty);const [editId,setEditId]=useState(null);const [search,setSearch]=useState("");const [filter,setFilter]=useState("All");const save=e=>{e.preventDefault();if(!form.name)return;if(editId)setEmployees(employees.map(x=>x.id===editId?{...form,id:editId}:x));else setEmployees([...employees,{...form,id:Date.now()}]);setForm(empty);setEditId(null)};const shown=employees.filter(x=>(filter==="All"||x.dept===filter)&&x.name.toLowerCase().includes(search.toLowerCase()));return <section><h1>Assignment 3: Employee Directory</h1><form className="form" onSubmit={save}>{["name","gender","phone","local","permanent"].map(k=><input key={k} name={k} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<select name="dept" value={form.dept} onChange={e=>setForm({...form,dept:e.target.value})}><option>IT</option><option>HR</option><option>Finance</option><option>Sales</option></select><button>{editId?"Update":"Add Employee"}</button></form><div className="toolbar"><input placeholder="Search employee" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>IT</option><option>HR</option><option>Finance</option><option>Sales</option></select><b>Count: {shown.length}</b></div><div className="grid">{shown.map(x=><div className="card" key={x.id}><h3>{x.name}</h3><p>{x.dept} • {x.gender}</p><p>{x.phone}</p><p>Local: {x.local}</p><p>Permanent: {x.permanent}</p><button onClick={()=>{setForm(x);setEditId(x.id)}}>Edit</button> <button className="danger" onClick={()=>setEmployees(employees.filter(e=>e.id!==x.id))}>Delete</button></div>)}</div></section>}

function A4(){const [city,setCity]=useState("");const [weather,setWeather]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");async function search(e){e.preventDefault();setLoading(true);setError("");setWeather(null);try{const key=import.meta.env.VITE_WEATHER_API_KEY;if(!key)throw new Error("Add VITE_WEATHER_API_KEY in Vercel Environment Variables to use live weather.");const r=await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${encodeURIComponent(city)}&appid=${key}&units=metric`);if(!r.ok)throw new Error("City not found");setWeather(await r.json())}catch(err){setError(err.message)}finally{setLoading(false)}}return <section><h1>Assignment 4: Weather Dashboard</h1><form className="form" onSubmit={search}><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Enter city"/><button>Search</button></form>{loading&&<p>Loading...</p>}{error&&<p className="error">{error}</p>}{weather&&<div className="card"><h2>{weather.name}</h2><img src={`https://openweathermap.org/img/wn/${weather.weather[0].icon}@2x.png`} alt="weather"/><p>Temperature: {weather.main.temp} °C</p><p>Humidity: {weather.main.humidity}%</p><p>Wind Speed: {weather.wind.speed} m/s</p><p>Weather: {weather.weather[0].description}</p><p>Sunrise: {new Date(weather.sys.sunrise*1000).toLocaleTimeString()}</p><p>Sunset: {new Date(weather.sys.sunset*1000).toLocaleTimeString()}</p></div>}</section>}

const products=[{id:1,name:"Laptop",price:50000},{id:2,name:"Headphone",price:2000},{id:3,name:"Mouse",price:800}];
function A5(){const [cart,setCart]=useState([]);const [coupon,setCoupon]=useState("");function add(p){setCart(c=>{const f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]})}const remove=id=>setCart(c=>c.filter(x=>x.id!==id));const update=(id,qty)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,Number(qty))}:x));const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);const discount=coupon.trim().toUpperCase()==="SAVE10"?subtotal*.1:0;const gst=(subtotal-discount)*.18;const total=subtotal-discount+gst;return <section><h1>Assignment 5: Online Shopping Cart</h1><div className="grid">{products.map(p=><div className="card" key={p.id}><h3>{p.name}</h3><p>₹{p.price}</p><button onClick={()=>add(p)}>Add to Cart</button></div>)}</div><h2>Cart</h2>{cart.map(x=><div className="row" key={x.id}><span>{x.name} — ₹{x.price}</span><input type="number" min="1" value={x.qty} onChange={e=>update(x.id,e.target.value)}/><button onClick={()=>remove(x.id)}>Remove</button></div>)}<input placeholder="Coupon: SAVE10" value={coupon} onChange={e=>setCoupon(e.target.value)}/><div className="summary"><p>Subtotal: ₹{subtotal.toFixed(2)}</p><p>Discount: ₹{discount.toFixed(2)}</p><p>GST (18%): ₹{gst.toFixed(2)}</p><h2>Grand Total: ₹{total.toFixed(2)}</h2></div></section>}

const seed=[{id:1,header:"React Assignment",description:"Complete React practice",priority:"High",category:"Academic",raised:new Date().toLocaleString(),due:"28 Aug 2026",status:"Pending"}];
function A6(){const [tasks,setTasks]=useState(()=>JSON.parse(localStorage.getItem("tasks")||"null")||seed);const [filter,setFilter]=useState("All");useEffect(()=>localStorage.setItem("tasks",JSON.stringify(tasks)),[tasks]);const visible=tasks.filter(t=>filter==="All"||t.status===filter);return <section><h1>Assignment 6: Task Manager</h1><div className="toolbar"><Link className="button" to="/a6/add">Add Task</Link><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Raised</option><option>Pending</option><option>Closed</option></select></div><Routes><Route path="/" element={<TaskList tasks={visible} setTasks={setTasks}/>}/><Route path="/add" element={<AddTask setTasks={setTasks}/>}/><Route path="/:id" element={<TaskDetails tasks={tasks} setTasks={setTasks}/>}/></Routes></section>}

function TaskList({tasks,setTasks}){return <div className="grid">{tasks.map(t=><div className="card" key={t.id}><h3>{t.header}</h3><p>{t.description}</p><p>{t.priority} • {t.category} • {t.status}</p><Link to={`/a6/${t.id}`}>View Details</Link><button onClick={()=>setTasks(ts=>ts.filter(x=>x.id!==t.id))}>Delete</button></div>)}</div>}
function AddTask({setTasks}){const nav=useNavigate();const [f,setF]=useState({header:"",description:"",priority:"Medium",category:"Academic",due:"28 Aug 2026"});function submit(e){e.preventDefault();setTasks(ts=>[...ts,{...f,id:Date.now(),raised:new Date().toLocaleString(),status:"Raised"}]);nav("/a6")}return <form className="form" onSubmit={submit}>{["header","description","due"].map(k=><input required key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Academic</option><option>Personal</option></select><button>Add Task</button></form>}
function TaskDetails({tasks,setTasks}){const {id}=useParams();const t=tasks.find(x=>x.id===Number(id));if(!t)return <p>Task not found.</p>;return <div className="card"><h2>{t.header}</h2><p>{t.description}</p><p>Priority: {t.priority}</p><p>Category: {t.category}</p><p>Raised: {t.raised}</p><p>Due: {t.due}</p><p>Status: {t.status}</p><button onClick={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,status:x.status==="Closed"?"Pending":"Closed"}:x))}>{t.status==="Closed"?"Reopen":"Complete"}</button></div>}

function A7(){const [user,setUser]=useState(()=>localStorage.getItem("authUser"));const login=u=>{localStorage.setItem("authUser",u);localStorage.setItem("token","demo-jwt-token");setUser(u)};const logout=()=>{localStorage.removeItem("authUser");localStorage.removeItem("token");setUser(null)};return <section><h1>Assignment 7: Authentication System</h1><Routes><Route path="/" element={user?<Navigate to="/a7/dashboard"/>:<Navigate to="/a7/login"/>}/><Route path="/login" element={<Login onLogin={login}/>}/><Route path="/dashboard" element={user?<div className="card"><h2>Welcome, {user}</h2><p>Protected Dashboard</p><p>Demo JWT token is stored in localStorage.</p><button onClick={logout}>Logout</button></div>:<Navigate to="/a7/login"/>}/></Routes></section>}
function Login({onLogin}){const nav=useNavigate();const [u,setU]=useState("");const [p,setP]=useState("");const [err,setErr]=useState("");const strength=p.length<4?"Weak":p.length<8?"Medium":"Strong";function submit(e){e.preventDefault();if(!u)return setErr("Username is required");if(!p)return setErr("Password is required");onLogin(u);nav("/a7/dashboard")}return <form className="form" onSubmit={submit}><h2>Login</h2><input required placeholder="Username" value={u} onChange={e=>setU(e.target.value)}/><input required type="password" placeholder="Password" value={p} onChange={e=>setP(e.target.value)}/>{p&&<p>Password Strength: <b>{strength}</b></p>}{err&&<p className="error">{err}</p>}<button>Login</button></form>}

export default function App(){return <BrowserRouter><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/a1" element={<A1/>}/><Route path="/a2" element={<A2/>}/><Route path="/a3" element={<A3/>}/><Route path="/a4" element={<A4/>}/><Route path="/a5" element={<A5/>}/><Route path="/a6/*" element={<A6/>}/><Route path="/a7/*" element={<A7/>}/></Routes></Layout></BrowserRouter>}